version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.2
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
      - run:
          command: |
            sudo apt-get update
            pipenv install
      - run:
          command: |
            pipenv run py.test